blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import LatestPostsFeed

urlpatterns = [
    # post views
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/' \
        r'(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
    url(r'^search/$', views.post_search, name='post_search'),
]

sblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls',
                           namespace='blog',
                           app_name='blog')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    to = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    comments = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control'}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'w-50 form-control'
            }
        ))

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
from django.db.models import Count
from haystack.query import SearchQuerySet


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts, 'page': page, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month,
                             publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to databaseyet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            return redirect('' + post.get_absolute_url())
    else:
        comment_form = CommentForm()
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids) \
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/details.html', {'post': post, 'comments': comments, 'comment_form': comment_form,
                                                      'similar_posts': similar_posts})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    cd = {}
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.co', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent, 'cd': cd})


def post_search(request):
    form = SearchForm()
    if 'query' in request.GET:
        form = SearchForm(request.GET)
    cd = {}
    results = None
    total_results = int()
    if form.is_valid():
        cd = form.cleaned_data
        results = SearchQuerySet().models(Post) \
            .filter(content=cd['query']).load_all()
        # count total results
        total_results = results.count()
    return render(request, 'blog/post/search.html',
                      {'form': form, 'cd': cd, 'results': results, 'total_results': total_results})

templates/blog/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap/bootstrap-grid.min.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap/bootstrap-reboot.min.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body class="container">
<div id="main" class="row">
    <div id="content" class="col-sm-8">

        {% block content %}
        {% endblock %}

    </div>
    <div id="sidebar" class="col-sm-3 offset-1">

        <h2>My blog</h2>
        <p>This is my blog. I've written {% total_posts %} posts so far.</p>
        <br>
        <div class="">
            <h4><a href="{% url 'blog:post_list' %}" class="list-group-item bg-info text-center, text-white">All
                Posts</a></h4>
        </div>
        <hr>
        <h3>Latest posts</h3>
        <br>
        {% show_latest_posts 2 %}
        <br>
        <h3>Most commented posts</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul class="list-group">
            {% for post in most_commented_posts %}
                <li class="list-group-item">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>
        <br>
        <span class="badge badge-info"><a href="{% url 'blog:post_feed' %}"
                                          class="text-white nav-link">RSS</a></span>
        <span class="badge badge-info "><a href="{% url 'django.contrib.sitemaps.views.sitemap' %}"
                                           class="text-white nav-link">Sitemap</a></span>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
        integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
        integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>

</body>
</html>

templates/blog/post/details.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date small font-italic">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown|linebreaks }}
    <p>
        <a href="{% url "blog:post_share" post.id %}" class="btn btn-outline-info">
            Share via mail
        </a>
    </p>
    <br>
    <div class="tag">
        {% for tag in post.tags.all %}
            <a href="{% url "blog:post_list_by_tag" tag.slug %}" class="badge badge-info"><i
                    class="fa fa-tag"></i> {{ tag }}</a>
        {% endfor %}
    </div>
    <br>
    <h3>Similar posts</h3>
    {% for post in similar_posts %}
        <p>
            <a class="list-group-item" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}
    <hr>
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="card card-block">
            <p class="card-title h4">
                {{ comment.name }}
            <div class="small font-italic">{{ comment.created }}</div>
            </p>
            <div class="card-text">
                {{ comment.body|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {% csrf_token %}
            {% for  field in  comment_form %}
                {% if field.errors %}
                    <div class=" form-group alert alert-danger alert-dismissable">
                        {{ field.errors }}
                    </div>
                {% endif %}
                <div class="form-group">
                    {{ field.label_tag }} {{ field }}
                </div>
            {% endfor %}
            <p><input type="submit" value="Add comment" class="btn btn-outline-info"></p>
        </form>
    {% endif %}
{% endblock %}

templates/blog/post/latest_posts.html
<ul class="list-group">
    {% for post in latest_posts %}
        <li class="list-group-item">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2 class="">
            <a href="{{ post.get_absolute_url }}" class="nav-link text-info">
                {{ post.title|Capitalize }}
            </a>
        </h2>
        <p class="date small font-italic">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords:30|linebreaks }}
        <br>
        <div class="tag">
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}" class="badge badge-info"><i
                        class="fa fa-tag"></i> {{ tag }}</a>
            {% endfor %}
        </div>
        <br>
    {% endfor %}

    {% include "blog/post/pagination.html" with page=posts %}
{% endblock %}

templates/blog/post/pagination.html
<nav aria-label="Page navigation example">
<ul class="pagination">
{% if page.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a></li>
{% endif %}
    <li class="page-item">
    <a class="page-link" href="#">{{ page.number }} of {{ page.paginator.num_pages }}</a>
    </li>
    {% if page.has_next %}
        <li class="page-item"><a class="page-link"  href="?page={{ page.next_page_number }}">Next</a></li>
    {% endif %}
</ul>
</nav>

templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}
{% block content %}

    {% if "query" in request.GET %}
        <h1>Posts containing "{{ cd.query }}"</h1>
        <h3>Found {{ total_results }} result{{ total_results|pluralize}}</h3>
        {% for result in results %}
            {% with post=result.object %}
                <h5><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
                {{ post.body|truncatewords:5 }}
            {% endwith %}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}" class="btn btn-outline-info">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search" class="btn btn-outline-info">
        </form>
    {% endif %}
{% endblock %}

templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ cd.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <div class="alert-danger">
                        {{ field.errors }}
                    </div>
                    {{ field.label_tag }} {{ field  }}
                </div>
            {% endfor %}

            <input type="submit" value="Send E-mail" class="btn btn-outline-info">
        </form>
    {% endif %}
{% endblock %}